name: Release & Deploy

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      issues: write
      pull-requests: write
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Install UV
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
    
    - name: Set up Python
      run: uv python install 3.13
    
    - name: Install dependencies
      run: uv sync --dev
    
    - name: Run tests before release
      run: |
        uv run pytest tests/unit/ -v
        uv run pytest tests/integration/ -v || true
    
    - name: Setup Node.js for semantic-release
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install semantic-release
      run: |
        npm install -g semantic-release
        npm install -g @semantic-release/changelog
        npm install -g @semantic-release/git
        npm install -g @semantic-release/github
    
    - name: Create semantic-release config
      run: |
        cat > .releaserc.json << 'EOF'
        {
          "branches": ["main"],
          "plugins": [
            "@semantic-release/commit-analyzer",
            "@semantic-release/release-notes-generator",
            "@semantic-release/changelog",
            "@semantic-release/github",
            ["@semantic-release/git", {
              "assets": ["CHANGELOG.md", "pyproject.toml"],
              "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
            }]
          ]
        }
        EOF
    
    - name: Run semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: semantic-release
    
    - name: Send deployment notification
      if: success()
      run: |
        echo "🚀 New release deployed successfully!"
        echo "Version: $(git describe --tags --abbrev=0)"
        echo "Commit: $(git rev-parse --short HEAD)"
      
  deploy:
    needs: release
    runs-on: ubuntu-latest
    if: success()
    
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
        fetch-depth: 0
    
    - name: Get latest release
      id: latest-release
      run: |
        LATEST_TAG=$(git describe --tags --abbrev=0)
        echo "tag=$LATEST_TAG" >> $GITHUB_OUTPUT
        echo "Latest release: $LATEST_TAG"
    
    - name: Update production automation workflow
      run: |
        echo "🔄 Production automation is now running on version ${{ steps.latest-release.outputs.tag }}"
        echo "The DNC automation workflow will use the latest code from main branch"
        echo "To schedule automation runs, configure the dnc-automation.yml workflow"
    
    - name: Deployment complete notification
      run: |
        echo "✅ Deployment complete!"
        echo "Version: ${{ steps.latest-release.outputs.tag }}"
        echo "Status: Production ready"
        echo "Next: Configure scheduled automation runs"